# GESSA DAVID
# ID 146d535d8501f000

## Tag along project Stage B

In [1]:
#importation of libraries
import numpy as np
import pandas as pd

In [2]:
#loading of the data
pd.set_option('display.max_columns',29)
energy_data=pd.read_csv("C:/Users/PROFFESSOR/Desktop/HAMOYE WORK/Stage B/QUIZ/energydata_complete.csv")

In [3]:
#shapshot of the data
energy_data.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,45.566667,17.166667,55.20,7.026667,84.256667,17.200000,41.626667,18.2,48.900000,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,45.992500,17.166667,55.20,6.833333,84.063333,17.200000,41.560000,18.2,48.863333,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,45.890000,17.166667,55.09,6.560000,83.156667,17.200000,41.433333,18.2,48.730000,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,45.723333,17.166667,55.09,6.433333,83.423333,17.133333,41.290000,18.1,48.590000,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,45.530000,17.200000,55.09,6.366667,84.893333,17.200000,41.230000,18.1,48.590000,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [4]:
#reformating of data
x_train= np.array(energy_data['T2']).reshape(-1,1)
y_train=np.array(energy_data['T6']).reshape(-1,1)

From the dataset, fit a linear model on the relationship between the temperature in the living room in Celsius (x = T2) and the temperature outside the building (y = T6). What is the R^2 value in two d.p.?

In [5]:
#importation of more libraries
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.2, random_state=1)

In [7]:
linear_model = LinearRegression()
linear_model.fit(x_train,y_train)

LinearRegression()

In [8]:
predicted_values = linear_model.predict(x_test)

In [9]:
r2_score = r2_score(y_test, predicted_values)
print(round(r2_score, 2) )

0.65

Question 13
Normalize the dataset using the MinMaxScaler after removing the following columns: [“date”, “lights”]. The target variable is “Appliances”. Use a 70-30 train-test set split with a random state of 42 (for reproducibility). Run a multiple linear regression using the training set and evaluate your model on the test set. Answer the following questions:

What is the Mean Absolute Error (in two decimal places)?

In [10]:
train_features = energy_data.drop(columns=['lights','date'],axis=1)

In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
train_features = pd.DataFrame(scaler.fit_transform(train_features), columns=train_features.columns)

In [12]:
#sample data
train_features.head()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,0.046729,0.32735,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,0.381691,0.381070,0.841827,0.170594,0.653428,0.173329,0.661412,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.046729,0.32735,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,0.381691,0.375443,0.839872,0.170594,0.651064,0.173329,0.660155,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.037383,0.32735,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,0.380037,0.367487,0.830704,0.170594,0.646572,0.173329,0.655586,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.037383,0.32735,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,0.380037,0.363800,0.833401,0.164310,0.641489,0.164175,0.650788,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.046729,0.32735,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,0.380037,0.361859,0.848264,0.170594,0.639362,0.164175,0.650788,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611

In [13]:
#create the target and training set
target_feature = train_features['Appliances']
train_features = train_features.drop(columns=['Appliances'],axis=1)

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(train_features, target_feature, test_size=0.3, random_state=42)

In [15]:
linear_model2 = LinearRegression()
linear_model2.fit(X_train,Y_train)

LinearRegression()

In [16]:
predicted_values2 = linear_model2.predict(X_test)

In [17]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(Y_test, predicted_values2)
print(round(mae, 2) )

0.05

Question 14

What is the Residual Sum of Squares (in two decimal places)?

In [18]:
rss = np.sum(np.square(Y_test - predicted_values2))
print(round(rss, 2))

45.35

Question 15

What is the Root Mean Squared Error (in three decimal places)?

In [19]:
from sklearn.metrics import  mean_squared_error
rmse = np.sqrt(mean_squared_error(Y_test, predicted_values2))
print(round(rmse, 3) )

0.088

Question 16
What is the Coefficient of Determination (in two decimal places)?

In [20]:
r2_score = r2_score(Y_test, predicted_values2)
print(round(r2_score, 2) )

0.15

Question 17
Obtain the feature weights from your linear model above. Which features have the lowest and highest weights respectively?

In [21]:
#function to compute weight 
def get_weights_df(model, feature, col_name):
    #this function returns the weight of every feature
    weights = pd.Series(model.coef_, feature.columns).sort_values() 
    weights_df = pd.DataFrame(weights).reset_index() 
    weights_df.columns = ['Features', col_name] 
    weights_df[col_name].round(3)
    return weights_df

In [22]:
#code showing feature weights on which to select  that with the lowest and highest weight.
linear_weights_df = get_weights_df(linear_model2, X_train, 'Linear_Model_Weight') 
linear_weights_df

       Features  Linear_Model_Weight
0          RH_2            -0.456698
1         T_out            -0.321860
2            T2            -0.236178
3            T9            -0.189941
4          RH_8            -0.157595
5        RH_out            -0.077671
6          RH_7            -0.044614
7          RH_9            -0.039800
8            T5            -0.015657
9            T1            -0.003281
10          rv1             0.000770
11          rv2             0.000770
12  Press_mm_hg             0.006839
13           T7             0.010319
14   Visibility             0.012307
15         RH_5             0.016006
16         RH_4             0.026386
17           T4             0.028981
18    Windspeed             0.029183
19         RH_6             0.038049
20         RH_3             0.096048
21           T8             0.101995
22    Tdewpoint             0.117758
23           T6             0.236425
24           T3             0.290627
25         RH_1             0.553547

Question 18

Train a ridge regression model with an alpha value of 0.4. Is there any change to the root mean squared error (RMSE) when evaluated on the test set?

In [23]:
from sklearn.linear_model import Ridge 
ridge_reg = Ridge(alpha=0.4) 
ridge_reg.fit(X_train, Y_train)

Ridge(alpha=0.4)

In [24]:
predicted_values3 = ridge_reg.predict(X_test)

In [25]:
rmse = np.sqrt(mean_squared_error(Y_test, predicted_values3))
print(round(rmse, 3) )

0.088

Question 19

Train a lasso regression model with an alpha value of 0.001 and obtain the new feature weights with it. How many of the features have non-zero feature weights

In [26]:
from sklearn.linear_model import Lasso 
lasso_reg = Lasso(alpha=0.001) 
lasso_reg.fit(X_train, Y_train)

Lasso(alpha=0.001)

In [27]:
#4 features have non zero weights
linear_weights_df = get_weights_df(lasso_reg, X_train, 'Lasso regression model') 
linear_weights_df

       Features  Lasso regression model
0        RH_out               -0.049557
1          RH_8               -0.000110
2            T1                0.000000
3     Tdewpoint                0.000000
4    Visibility                0.000000
5   Press_mm_hg               -0.000000
6         T_out                0.000000
7          RH_9               -0.000000
8            T9               -0.000000
9            T8                0.000000
10         RH_7               -0.000000
11          rv1               -0.000000
12           T7               -0.000000
13           T6                0.000000
14         RH_5                0.000000
15           T5               -0.000000
16         RH_4                0.000000
17           T4               -0.000000
18         RH_3                0.000000
19           T3                0.000000
20         RH_2               -0.000000
21           T2                0.000000
22         RH_6               -0.000000
23          rv2               -0.000000
24    Windspeed                0.002912
25         RH_1                0.017880

In [29]:
predicted_values4 = lasso_reg.predict(X_test)

Question 20

What is the new RMSE with the lasso regression? (Answer should be in three (3) decimal places)

In [30]:
rmse = np.sqrt(mean_squared_error(Y_test, predicted_values4))
print(round(rmse, 3) )

0.094